# Resource quotas for network function namespaces
# Adjust based on your hardware capacity

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ran-quota
  namespace: openairinterface
spec:
  hard:
    requests.cpu: "20"      # Adjust for your node capacity
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-quota
  namespace: free5gc
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: openairinterface
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "500m"
      memory: 1Gi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: free5gc
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "500m"
      memory: 1Gi
    type: Container